language: scala
scala:
    - 2.12.1
before_install:
- export TZ=UTC
script:
    - ./buildWithCoverage.sh
    - sbt coveralls
jdk:
  - oraclejdk8
after_success:
  - bash <(curl -s https://codecov.io/bash)